version: 2.1
defaults: &defaults
  docker:
    - image: circleci/clojure:openjdk-11-lein-node

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: ./scripts/ci
          when: always
      - store_artifacts:
          path: ~/video
      - run: ls target -lh
      - persist_to_workspace:
          root: '.'
          paths:
            - target

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: ./scripts/deploy.sh

  babashka:
    <<: *defaults
    steps:
      - attach_workspace:
          at: '.'
      - run: wget https://github.com/borkdude/babashka/releases/download/v0.1.3/babashka-0.1.3-linux-amd64.zip
      - run: unzip babashka*zip
      - run: bb --socket-repl 4444 &
      - run: node target/fixture.js babashka.bb

workflows:
  version: 2
  default-workflow:
    jobs:
      - test:
          filters:
            tags:
              only:
                - /^v.+/

      - publish:
          context: Clojure Libs
          requires:
            - test
          filters:
            tags:
              only:
                - /^v.+/
            branches:
              only:
                - master

      - babashka:
          requires:
            - test
