version: 2.1
defaults: &defaults
  docker:
    - image: circleci/clojure:openjdk-11-lein-node

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: ./scripts/ci
          when: always
      - store_artifacts:
          path: ~/video
      - run: ls target -lh
      - persist_to_workspace:
          root: '.'
          paths:
            - target
            - node_modules

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: ./scripts/deploy.sh

  babashka:
    <<: *defaults
    steps:
      - attach_workspace:
          at: '.'
      - run: wget https://github.com/borkdude/babashka/releases/download/v0.1.3/babashka-0.1.3-linux-amd64.zip
      - run: unzip babashka*zip
      - run: ./bb --socket-repl 4444 & sleep 2; node target/fixture.js babashka.bb

  joker:
    <<: *defaults
    steps:
      - attach_workspace:
          at: '.'
      - run: wget https://github.com/candid82/joker/releases/download/v0.15.6/joker-0.15.6-linux-amd64.zip
      - run: unzip joker*.zip
      - run: ./joker --exit-to-repl localhost:4444 & sleep 2; node target/fixture.js joker.joke

  lumo:
    <<: *defaults
    steps:
      - attach_workspace:
          at: '.'
      - run: sudo npm install -g lumo-cljs
      - run: lumo -n 4444 & sleep 20; node target/fixture.js lumo.cljs

  clojerl:
    docker:
      - image: erlang
    steps:
      - attach_workspace:
          at: '.'
      - run: apt-get update
      - run: apt-get install -y git npm nodejs rlwrap tmux
      - run: echo '{erl_opts, [debug_info]}. {deps, [{clojerl, {git, "https://github.com/clojerl/clojerl", {branch, "master"}}}]}. {plugins, [{rebar3_clojerl, "0.8.3"}]}.' > rebar.config
      - run: echo ":foo" | rebar3 clojerl repl
      - run: tmux new-session -d
      - run: tmux send-keys 'rebar3 clojerl repl' Enter
      - run: tmux send-keys "(do (require 'clojure.core.server) (clojure.core.server/start-server {:name \"socket-repl\" :port 4444 :accept 'clojure.main/repl :address \"localhost\"}))" Enter
      - run: sleep 20; node target/fixture.js clojerl.clje

workflows:
  version: 2
  default-workflow:
    jobs:
      - test:
          filters:
            tags:
              only:
                - /^v.+/

      - publish:
          context: Clojure Libs
          requires:
            - test
          filters:
            tags:
              only:
                - /^v.+/
            branches:
              only:
                - master

      - babashka:
          requires:
            - test
      - joker:
          requires:
            - test
      - lumo:
          requires:
            - test
      - clojerl:
          requires:
            - test
